version: '2.2'

services:
  dynamic-qr:
    build: .
    image: dynamic-qr
    ports:
      - 3000:3000
    environment:
      # Port for the server to listen to
      - LISTEN_PORT=3000

      # The base URL for the application
      - BASE_URL=http://localhost:3000/
    restart: always
    volumes:
      - ./data:/app/data/
